SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (1, N'Kayak', N'A boat for one person', CAST(275.00 AS Decimal(18, 2)), N'Watersports', <Binary Data>, N'image/png')
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (2, N'Lifejacket', N'Protective and Fashionable', CAST(48.95 AS Decimal(18, 2)), N'Watersports', <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (3, N'Soccerball', N'Fifa-approved size and weight', CAST(19.50 AS Decimal(18, 2)), N'Soccer', <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (4, N'Corner Flags', N'Give your plying field a professional touch', CAST(34.95 AS Decimal(18, 2)), N'Soccer', <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (5, N'Stadium', N'Flat-packed, 35,000-seat stadium', CAST(79500.00 AS Decimal(18, 2)), N'Soccer', <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (6, N'Thinking Cap', N'Improve your brain efficiency by 75%', CAST(16.00 AS Decimal(18, 2)), N'Chess', <Binary Data>, N'image/jpeg')
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (7, N'Unsteady Chair', N'Secretly give your opponent a disadvantage', CAST(29.95 AS Decimal(18, 2)), N'Chess', <SQLVARIANT>, NULL)
INSERT INTO [dbo].[Products] ([ProductID], [Name], [Description], [Price], [Category], [ImageData], [ImageMimeType]) VALUES (8, N'Human Chess Board', N'A fun game for the family', CAST(75.00 AS Decimal(18, 2)), N'Chess', <SQLVARIANT>, NULL)
SET IDENTITY_INSERT [dbo].[Products] OFF
